inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/test_app_templates/**/*'
    - 'vendor/**/*'
    - 'lib/hyrax/specs/**/*'

Lint/HandleExceptions:
  Exclude:
    - 'spec/unit/**/*'
    - 'spec/integration/**/*'

Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['included']
  Exclude:
    - 'valkyrie_active_fedora.gemspec'
    - 'lib/tasks/*.rake'
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/Semicolon:
  Exclude:
    - 'spec/**/*'

Style/Lambda:
  Exclude:
    - 'spec/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'spec/unit/base_spec.rb'

Style/SignalException:
  Enabled: false

Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - 'lib/generators/**/*'

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

RSpec/NotToNot:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false
