language: ruby
cache: bundler
sudo: false
rvm: 2.5
env:
  matrix:
    - "RAILS_VERSION=5.1.6"
    - "RAILS_VERSION=5.0.7"
global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - jdk_switcher use oraclejdk8
